version: '2.1'

services:

  exchange:
    build: ./exchange
    ports:
      - "5000:5000"

  btc-spring-app:
    build: ./btc-spring-app
    depends_on:
      - db
    ports:
      - "5010:8080"
    networks:
      - mysql

  db:
    image: mysql:8.0.13
    container_name: mysql
    restart: always
    ports:
      - 3310:3306
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: icoder_pwd
      MYSQL_DATABASE: icoder_db
      MYSQL_USER: icoder_user
      MYSQL_PASSWORD: icoder_pwd
    networks:
      - mysql


networks:
  mysql: